//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASM_SCAU.configs{
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class AppMainSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppMainSettings defaultInstance = ((AppMainSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppMainSettings())));
        
        public static AppMainSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("vs")]
        public string EditorTheme {
            get {
                return ((string)(this["EditorTheme"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstOpen {
            get {
                return ((bool)(this["FirstOpen"]));
            }
            set {
                this["FirstOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:/ASMCompiler")]
        public string CompilerPath {
            get {
                return ((string)(this["CompilerPath"]));
            }
            set {
                this["CompilerPath"] = value;
            }
        }
    }
}
