//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MASM_SCAU.configs {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class ASMScripts : global::System.Configuration.ApplicationSettingsBase {
        
        private static ASMScripts defaultInstance = ((ASMScripts)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ASMScripts())));
        
        public static ASMScripts Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[sdl]
fullscreen=false
fulldouble=false
fullresolution=original
windowresolution=original
output=surface
autolock=true
sensitivity=100
waitonerror=true
priority=higher,normal
mapperfile=mapper-0.74.map
usescancodes=true

[dosbox]
language=
machine=svga_s3
captures=capture
memsize=16

[render]
frameskip=0
aspect=false
scaler=normal2x

[cpu]
core=auto
cputype=auto
cycles=auto
cycleup=10
cycledown=20

[mixer]
nosound=false
rate=44100
blocksize=1024
prebuffer=20

[midi]
mpu401=intelligent
mididevice=default
midiconfig=

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5
sbmixer=true
oplmode=auto
oplemu=default
oplrate=44100

[gus]
gus=false
gusrate=44100
gusbase=240
gusirq=5
gusdma=3
ultradir=C:\ULTRASND

[speaker]
pcspeaker=true
pcrate=44100
tandy=auto
tandyrate=44100
disney=true

[joystick]
joysticktype=auto
timed=true
autofire=false
swap34=false
buttonwrap=false

[serial]
serial1=dummy
serial2=dummy
serial3=disabled
serial4=disabled

[dos]
xms=true
ems=true
umb=true
keyboardlayout=auto

[ipx]
ipx=false

[autoexec]
MOUNT C &&SYSTEM32&&       
set PATH=$PATH$;&&SYSTEM32&&
C:\
cls
masm App.asm App.obj LOG.lst LOG.crf>LOG.log
cls
link App.obj;
cd>FIN.tlg
cls
@echo off
App.exe
delete App.exe
@echo.
pause
EXIT
")]
        public string startScript {
            get {
                return ((string)(this["startScript"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"[sdl]
fullscreen=false
fulldouble=false
fullresolution=original
windowresolution=original
output=surface
autolock=true
sensitivity=100
waitonerror=true
priority=higher,normal
mapperfile=mapper-0.74.map
usescancodes=true

[dosbox]
language=
machine=svga_s3
captures=capture
memsize=16

[render]
frameskip=0
aspect=false
scaler=normal2x

[cpu]
core=auto
cputype=auto
cycles=auto
cycleup=10
cycledown=20

[mixer]
nosound=false
rate=44100
blocksize=1024
prebuffer=20

[midi]
mpu401=intelligent
mididevice=default
midiconfig=

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5
sbmixer=true
oplmode=auto
oplemu=default
oplrate=44100

[gus]
gus=false
gusrate=44100
gusbase=240
gusirq=5
gusdma=3
ultradir=C:\ULTRASND

[speaker]
pcspeaker=true
pcrate=44100
tandy=auto
tandyrate=44100
disney=true

[joystick]
joysticktype=auto
timed=true
autofire=false
swap34=false
buttonwrap=false

[serial]
serial1=dummy
serial2=dummy
serial3=disabled
serial4=disabled

[dos]
xms=true
ems=true
umb=true
keyboardlayout=auto

[ipx]
ipx=false

[autoexec]
MOUNT C &&SYSTEM32&&       
set PATH=$PATH$;&&SYSTEM32&&
C:\
CLS
cls
masm App.asm App.obj LOG.lst LOG.crf>LOG.log
cls
link App.obj;
cd>FIN.tlg
delete App.asm
cls
@echo off
debug App.exe
delete App.exe
@echo.
pause
EXIT

")]
        public string debugScript {
            get {
                return ((string)(this["debugScript"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"DATAS SEGMENT
    ;此处输入数据段代码  
DATAS ENDS

STACKS SEGMENT
    ;此处输入堆栈段代码
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,SS:STACKS
START:
    MOV AX,DATAS
    MOV DS,AX
    ;此处输入代码段代码
    MOV AH,4CH
    INT 21H
CODES ENDS
    END START")]
        public string newCodeScript {
            get {
                return ((string)(this["newCodeScript"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<!DOCTYPE html>
<html>
<head>
	<meta http-equiv=""X-UA-Compatible"" content=""IE=edge"" />
	<meta http-equiv=""Content-Type"" content=""text/html;charset=utf-8"" >
	<link rel=""stylesheet"" data-name=""vs/editor/editor.main"" href=""../node_modules/monaco-editor/min/vs/editor/editor.main.css"">
	<link rel=""stylesheet"" href=""st.css""><!--禁用滚动条-->

</head>
<!--body style=""background-color: #1E1E1E;font-size: large;""-->
<body style=""background-color: #f3f3f3;font-size: large;font-family:'微软雅黑', Tahoma, Geneva, Verdana, sans-serif;"">
<div id=""container"" style=""width:100%;height:702px;margin:0""></div>
<script>var require = { paths: { 'vs': '../node_modules/monaco-editor/min/vs' } };</script>
<script src=""../node_modules/monaco-editor/min/vs/loader.js""></script>
<script src=""../node_modules/monaco-editor/min/vs/editor/editor.main.nls.js""></script>
<script src=""../node_modules/monaco-editor/min/vs/editor/editor.main.js""></script>


<script>

	var editor = monaco.editor.create(document.getElementById('container'), {
		value: [
#CODECONTENT#
		].join('\n'),
		language: 'abap',
		automaticLayout: true
	});
	monaco.editor.setTheme('#THEME#'); // hc-black vs-dark vs


</script>

</body>
</html>")]
        public string htmlSourceScript {
            get {
                return ((string)(this["htmlSourceScript"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<!DOCTYPE html>\r\n<html lang=\"zh-cn\">\r\n\r\n<head>\r\n\t<meta http-equiv=\"Content-Type\" " +
            "content=\"text/html; charset=UTF-8\">\r\n\t<meta name=\"viewport\" content=\"width=devic" +
            "e-width\">\r\n\t<title>Monaco Editor</title>\r\n\t<link data-name=\"vs/editor/editor.mai" +
            "n\" rel=\"stylesheet\" href=\"../node_modules/monaco-editor/min/vs/editor/editor.mai" +
            "n.css\">\r\n</head>\r\n<style>/*!\r\n  * Bootstrap v2.3.0\r\n  *\r\n  * Copyright 2012 Twit" +
            "ter, Inc\r\n  * Licensed under the Apache License v2.0\r\n  * http://www.apache.org/" +
            "licenses/LICENSE-2.0\r\n  *\r\n  * Designed and built with all the love in the world" +
            " @twitter by @mdo and @fat.\r\n  */footer,nav,section{display:block}html{font-size" +
            ":100%;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}a:focus{outline:th" +
            "in dotted #333;outline:5px auto -webkit-focus-ring-color;outline-offset:-2px}a:a" +
            "ctive,a:hover{outline:0}img{height:auto;max-width:100%;vertical-align:middle;bor" +
            "der:0;-ms-interpolation-mode:bicubic}button,input,select{margin:0;font-size:100%" +
            ";vertical-align:middle}button,input{line-height:normal}button::-moz-focus-inner," +
            "input::-moz-focus-inner{padding:0;border:0}button{cursor:pointer;-webkit-appeara" +
            "nce:button}button,input[type=checkbox],label,select{cursor:pointer}@media print{" +
            "*{color:#000!important;text-shadow:none!important;background:0 0!important;box-s" +
            "hadow:none!important}a,a:visited{text-decoration:underline}a[href]:after{content" +
            ":\" (\" attr(href) \")\"}pre{border:1px solid #999;page-break-inside:avoid}img{page-" +
            "break-inside:avoid}img{max-width:100%!important}@page{margin:.5cm}h3,p{orphans:3" +
            ";widows:3}h3{page-break-after:avoid}}body{margin:0;line-height:20px;color:#555;b" +
            "ackground-color:#fff}a{color:#007fff;text-decoration:none}a:focus,a:hover{color:" +
            "#06c;text-decoration:underline}.row{margin-left:-20px}.row:after,.row:before{dis" +
            "play:table;line-height:0;content:\"\"}.row:after{clear:both}[class*=span]{float:le" +
            "ft;min-height:1px;margin-left:20px}.container,.navbar-fixed-top .container{width" +
            ":940px}.span12{width:940px}.span9{width:700px}.span8{width:620px}.span4{width:30" +
            "0px}.span3{width:220px}.container{margin-right:auto;margin-left:auto}.container:" +
            "after,.container:before{display:table;line-height:0;content:\"\"}.container:after{" +
            "clear:both}p{margin:0 0 10px}small{font-size:85%}strong{font-weight:700}.text-ce" +
            "nter{text-align:center}h3,h4{margin:10px 0;font-family:inherit;font-weight:300;l" +
            "ine-height:20px;color:#080808;text-rendering:optimizelegibility}h3{line-height:4" +
            "0px}h3{font-size:24.5px}h4{font-size:17.5px}ul{padding:0;margin:0 0 10px 25px}li" +
            "{line-height:20px}hr{margin:20px 0;border:0;border-top:1px solid #eee;border-bot" +
            "tom:1px solid #fff}pre{padding:0 3px 2px;font-family:Monaco,Menlo,Consolas,\"Cour" +
            "ier New\",monospace;font-size:12px;color:#999;-webkit-border-radius:3px;-moz-bord" +
            "er-radius:3px;border-radius:3px}pre{display:block;padding:9.5px;margin:0 0 10px;" +
            "font-size:13px;line-height:20px;word-break:break-all;word-wrap:break-word;white-" +
            "space:pre;white-space:pre-wrap;background-color:#f5f5f5;border:1px solid #ccc;bo" +
            "rder:1px solid rgba(0,0,0,.15);-webkit-border-radius:0;-moz-border-radius:0;bord" +
            "er-radius:0}button,input,label,select{font-size:14px;font-weight:400;line-height" +
            ":20px}button,input,select{font-family:\"Open Sans\",Calibri,Candara,Arial,sans-ser" +
            "if}label{display:block;margin-bottom:5px}select{display:inline-block;height:20px" +
            ";padding:4px 6px;margin-bottom:10px;font-size:14px;line-height:20px;color:#bbb;v" +
            "ertical-align:middle;-webkit-border-radius:0;-moz-border-radius:0;border-radius:" +
            "0}input{width:206px}input[type=checkbox]{margin:4px 0 0;line-height:normal}input" +
            "[type=checkbox]{width:auto}select{height:30px;line-height:30px}select{width:220p" +
            "x;background-color:#fff;border:1px solid #bbb}input[type=checkbox]:focus,select:" +
            "focus{outline:thin dotted #333;outline:5px auto -webkit-focus-ring-color;outline" +
            "-offset:-2px}input:-moz-placeholder{color:#bbb}input:-ms-input-placeholder{color" +
            ":#bbb}input::-webkit-input-placeholder{color:#bbb}.checkbox{min-height:20px;padd" +
            "ing-left:20px}.checkbox input[type=checkbox]{float:left;margin-left:-20px}input{" +
            "margin-left:0}input:focus:invalid,select:focus:invalid{color:#b94a48;border-colo" +
            "r:#ee5f5b}input:focus:invalid:focus,select:focus:invalid:focus{border-color:#e93" +
            "22d;-webkit-box-shadow:0 0 6px #f8b9b7;-moz-box-shadow:0 0 6px #f8b9b7;box-shado" +
            "w:0 0 6px #f8b9b7}[class^=icon-]{display:inline-block;width:14px;height:14px;mar" +
            "gin-top:1px;line-height:14px;vertical-align:text-top;background-image:url(../img" +
            "/glyphicons-halflings.png);background-position:14px 14px;background-repeat:no-re" +
            "peat}.collapse{position:relative;height:0;overflow:hidden;-webkit-transition:hei" +
            "ght .35s ease;-moz-transition:height .35s ease;-o-transition:height .35s ease;tr" +
            "ansition:height .35s ease}.btn{display:inline-block;padding:4px 12px;margin-bott" +
            "om:0;font-size:14px;line-height:20px;color:#999;text-align:center;text-shadow:0 " +
            "1px 1px rgba(255,255,255,.75);vertical-align:middle;cursor:pointer;background-co" +
            "lor:#dfdfdf;background-image:-moz-linear-gradient(top,#eee,#c8c8c8);background-i" +
            "mage:-webkit-gradient(linear,0 0,0 100%,from(#eee),to(#c8c8c8));background-image" +
            ":-webkit-linear-gradient(top,#eee,#c8c8c8);background-image:-o-linear-gradient(t" +
            "op,#eee,#c8c8c8);background-image:linear-gradient(to bottom,#eee,#c8c8c8);backgr" +
            "ound-repeat:repeat-x;border:1px solid #bbb;border-color:#c8c8c8 #c8c8c8 #a2a2a2;" +
            "border-color:rgba(0,0,0,.1) rgba(0,0,0,.1) rgba(0,0,0,.25);border-bottom-color:#" +
            "a2a2a2;-webkit-border-radius:0;-moz-border-radius:0;border-radius:0;-webkit-box-" +
            "shadow:inset 0 1px 0 rgba(255,255,255,.2),0 1px 2px rgba(0,0,0,.05);-moz-box-sha" +
            "dow:inset 0 1px 0 rgba(255,255,255,.2),0 1px 2px rgba(0,0,0,.05);box-shadow:inse" +
            "t 0 1px 0 rgba(255,255,255,.2),0 1px 2px rgba(0,0,0,.05)}.btn:active,.btn:focus," +
            ".btn:hover{color:#999;background-color:#c8c8c8}.btn:focus,.btn:hover{color:#999;" +
            "text-decoration:none;background-position:0 -15px;-webkit-transition:background-p" +
            "osition .1s linear;-moz-transition:background-position .1s linear;-o-transition:" +
            "background-position .1s linear;transition:background-position .1s linear}.btn:fo" +
            "cus{outline:thin dotted #333;outline:5px auto -webkit-focus-ring-color;outline-o" +
            "ffset:-2px}.btn:active{background-image:none;outline:0;-webkit-box-shadow:inset " +
            "0 2px 4px rgba(0,0,0,.15),0 1px 2px rgba(0,0,0,.05);-moz-box-shadow:inset 0 2px " +
            "4px rgba(0,0,0,.15),0 1px 2px rgba(0,0,0,.05);box-shadow:inset 0 2px 4px rgba(0," +
            "0,0,.15),0 1px 2px rgba(0,0,0,.05)}button.btn::-moz-focus-inner{padding:0;border" +
            ":0}.alert{padding:8px 35px 8px 14px;margin-bottom:20px;text-shadow:0 1px 0 rgba(" +
            "255,255,255,.5);background-color:#ff7518;border:1px solid transparent;-webkit-bo" +
            "rder-radius:0;-moz-border-radius:0;border-radius:0}.alert,.alert h4{color:#fff}." +
            "alert h4{margin:0}.alert .close{position:relative;top:-2px;right:-21px;line-heig" +
            "ht:20px}.alert-success{color:#fff;background-color:#3fb618;border-color:transpar" +
            "ent}.alert-success h4{color:#fff}.alert-danger,.alert-error{color:#fff;backgroun" +
            "d-color:#ff0039;border-color:transparent}.alert-danger h4,.alert-error h4{color:" +
            "#fff}.alert-info{color:#fff;background-color:#9954bb;border-color:transparent}.a" +
            "lert-info h4{color:#fff}.alert-block{padding-top:14px;padding-bottom:14px}.alert" +
            "-block>p,.alert-block>ul{margin-bottom:0}.alert-block p+p{margin-top:5px}.nav{ma" +
            "rgin-bottom:20px;margin-left:0;list-style:none}.nav>li>a{display:block}.nav>li>a" +
            ":focus,.nav>li>a:hover{text-decoration:none;background-color:#eee}.navbar{margin" +
            "-bottom:20px;overflow:visible}.navbar-inner{min-height:50px;padding-right:20px;p" +
            "adding-left:20px;background-color:#080808;background-image:-moz-linear-gradient(" +
            "top,#080808,#080808);background-image:-webkit-gradient(linear,0 0,0 100%,from(#0" +
            "80808),to(#080808));background-image:-webkit-linear-gradient(top,#080808,#080808" +
            ");background-image:-o-linear-gradient(top,#080808,#080808);background-image:line" +
            "ar-gradient(to bottom,#080808,#080808);background-repeat:repeat-x;border:1px sol" +
            "id transparent;-webkit-border-radius:0;-moz-border-radius:0;border-radius:0;-web" +
            "kit-box-shadow:0 1px 4px rgba(0,0,0,.065);-moz-box-shadow:0 1px 4px rgba(0,0,0,." +
            "065);box-shadow:0 1px 4px rgba(0,0,0,.065)}.navbar-inner:after,.navbar-inner:bef" +
            "ore{display:table;line-height:0;content:\"\"}.navbar-inner:after{clear:both}.navba" +
            "r .container{width:auto}.nav-collapse.collapse{height:auto;overflow:visible}.nav" +
            "bar .btn{margin-top:10px}.navbar-fixed-top{position:fixed;right:0;left:0;z-index" +
            ":1030;margin-bottom:0}.navbar-fixed-top .navbar-inner{border-width:0 0 1px}.navb" +
            "ar-fixed-top .navbar-inner{padding-right:0;padding-left:0;-webkit-border-radius:" +
            "0;-moz-border-radius:0;border-radius:0}.navbar-fixed-top .container{width:940px}" +
            ".navbar-fixed-top{top:0}.navbar-fixed-top .navbar-inner{-webkit-box-shadow:0 1px" +
            " 10px rgba(0,0,0,.1);-moz-box-shadow:0 1px 10px rgba(0,0,0,.1);box-shadow:0 1px " +
            "10px rgba(0,0,0,.1)}.navbar .nav{position:relative;left:0;display:block;float:le" +
            "ft;margin:0 10px 0 0}.navbar .nav>li{float:left}.navbar .nav>li>a{float:none;pad" +
            "ding:15px 15px 15px;color:#fff;text-decoration:none;text-shadow:0 1px 0 #080808}" +
            ".navbar .nav>li>a:focus,.navbar .nav>li>a:hover{color:#bbb;text-decoration:none;" +
            "background-color:rgba(0,0,0,.05)}.navbar .btn-navbar{display:none;float:right;pa" +
            "dding:7px 10px;margin-right:5px;margin-left:5px;color:#fff;text-shadow:0 -1px 0 " +
            "rgba(0,0,0,.25);background-color:#000;background-image:-moz-linear-gradient(top," +
            "#000,#000);background-image:-webkit-gradient(linear,0 0,0 100%,from(#000),to(#00" +
            "0));background-image:-webkit-linear-gradient(top,#000,#000);background-image:-o-" +
            "linear-gradient(top,#000,#000);background-image:linear-gradient(to bottom,#000,#" +
            "000);background-repeat:repeat-x;border-color:#000 #000 #000;border-color:rgba(0," +
            "0,0,.1) rgba(0,0,0,.1) rgba(0,0,0,.25);-webkit-box-shadow:inset 0 1px 0 rgba(255" +
            ",255,255,.1),0 1px 0 rgba(255,255,255,.075);-moz-box-shadow:inset 0 1px 0 rgba(2" +
            "55,255,255,.1),0 1px 0 rgba(255,255,255,.075);box-shadow:inset 0 1px 0 rgba(255," +
            "255,255,.1),0 1px 0 rgba(255,255,255,.075)}.navbar .btn-navbar:active,.navbar .b" +
            "tn-navbar:focus,.navbar .btn-navbar:hover{color:#fff;background-color:#000}.navb" +
            "ar .btn-navbar .icon-bar{display:block;width:18px;height:2px;background-color:#f" +
            "5f5f5;-webkit-border-radius:1px;-moz-border-radius:1px;border-radius:1px;-webkit" +
            "-box-shadow:0 1px 0 rgba(0,0,0,.25);-moz-box-shadow:0 1px 0 rgba(0,0,0,.25);box-" +
            "shadow:0 1px 0 rgba(0,0,0,.25)}.btn-navbar .icon-bar+.icon-bar{margin-top:3px}.n" +
            "avbar-inverse .navbar-inner{background-color:#007fff;background-image:-moz-linea" +
            "r-gradient(top,#007fff,#007fff);background-image:-webkit-gradient(linear,0 0,0 1" +
            "00%,from(#007fff),to(#007fff));background-image:-webkit-linear-gradient(top,#007" +
            "fff,#007fff);background-image:-o-linear-gradient(top,#007fff,#007fff);background" +
            "-image:linear-gradient(to bottom,#007fff,#007fff);background-repeat:repeat-x;bor" +
            "der-color:transparent}.navbar-inverse .nav>li>a{color:#fff;text-shadow:0 -1px 0 " +
            "rgba(0,0,0,.25)}.navbar-inverse .nav>li>a:focus,.navbar-inverse .nav>li>a:hover{" +
            "color:#fff}.navbar-inverse .nav>li>a:focus,.navbar-inverse .nav>li>a:hover{color" +
            ":#fff;background-color:rgba(0,0,0,.05)}.navbar-inverse .btn-navbar{color:#fff;te" +
            "xt-shadow:0 -1px 0 rgba(0,0,0,.25);background-color:#0072e6;background-image:-mo" +
            "z-linear-gradient(top,#0072e6,#0072e6);background-image:-webkit-gradient(linear," +
            "0 0,0 100%,from(#0072e6),to(#0072e6));background-image:-webkit-linear-gradient(t" +
            "op,#0072e6,#0072e6);background-image:-o-linear-gradient(top,#0072e6,#0072e6);bac" +
            "kground-image:linear-gradient(to bottom,#0072e6,#0072e6);background-repeat:repea" +
            "t-x;border-color:#0072e6 #0072e6 #004c99;border-color:rgba(0,0,0,.1) rgba(0,0,0," +
            ".1) rgba(0,0,0,.25)}.navbar-inverse .btn-navbar:active,.navbar-inverse .btn-navb" +
            "ar:focus,.navbar-inverse .btn-navbar:hover{color:#fff;background-color:#0072e6}@" +
            "-webkit-keyframes progress-bar-stripes{from{background-position:40px 0}to{backgr" +
            "ound-position:0 0}}@-moz-keyframes progress-bar-stripes{from{background-position" +
            ":40px 0}to{background-position:0 0}}@-ms-keyframes progress-bar-stripes{from{bac" +
            "kground-position:40px 0}to{background-position:0 0}}@-o-keyframes progress-bar-s" +
            "tripes{from{background-position:0 0}to{background-position:40px 0}}@keyframes pr" +
            "ogress-bar-stripes{from{background-position:40px 0}to{background-position:0 0}}." +
            "progress{height:20px;margin-bottom:20px;overflow:hidden;background-color:#f7f7f7" +
            ";background-image:-moz-linear-gradient(top,#f5f5f5,#f9f9f9);background-image:-we" +
            "bkit-gradient(linear,0 0,0 100%,from(#f5f5f5),to(#f9f9f9));background-image:-web" +
            "kit-linear-gradient(top,#f5f5f5,#f9f9f9);background-image:-o-linear-gradient(top" +
            ",#f5f5f5,#f9f9f9);background-image:linear-gradient(to bottom,#f5f5f5,#f9f9f9);ba" +
            "ckground-repeat:repeat-x;-webkit-border-radius:0;-moz-border-radius:0;border-rad" +
            "ius:0;-webkit-box-shadow:inset 0 1px 2px rgba(0,0,0,.1);-moz-box-shadow:inset 0 " +
            "1px 2px rgba(0,0,0,.1);box-shadow:inset 0 1px 2px rgba(0,0,0,.1)}.progress .bar{" +
            "float:left;width:0;height:100%;font-size:12px;color:#fff;text-align:center;text-" +
            "shadow:0 -1px 0 rgba(0,0,0,.25);background-color:#0e90d2;background-image:-moz-l" +
            "inear-gradient(top,#149bdf,#0480be);background-image:-webkit-gradient(linear,0 0" +
            ",0 100%,from(#149bdf),to(#0480be));background-image:-webkit-linear-gradient(top," +
            "#149bdf,#0480be);background-image:-o-linear-gradient(top,#149bdf,#0480be);backgr" +
            "ound-image:linear-gradient(to bottom,#149bdf,#0480be);background-repeat:repeat-x" +
            ";-webkit-box-shadow:inset 0 -1px 0 rgba(0,0,0,.15);-moz-box-shadow:inset 0 -1px " +
            "0 rgba(0,0,0,.15);box-shadow:inset 0 -1px 0 rgba(0,0,0,.15);-webkit-box-sizing:b" +
            "order-box;-moz-box-sizing:border-box;box-sizing:border-box;-webkit-transition:wi" +
            "dth .6s ease;-moz-transition:width .6s ease;-o-transition:width .6s ease;transit" +
            "ion:width .6s ease}.progress-striped .bar{background-color:#149bdf;background-im" +
            "age:-webkit-gradient(linear,0 100%,100% 0,color-stop(.25,rgba(255,255,255,.15))," +
            "color-stop(.25,transparent),color-stop(.5,transparent),color-stop(.5,rgba(255,25" +
            "5,255,.15)),color-stop(.75,rgba(255,255,255,.15)),color-stop(.75,transparent),to" +
            "(transparent));background-image:-webkit-linear-gradient(45deg,rgba(255,255,255,." +
            "15) 25%,transparent 25%,transparent 50%,rgba(255,255,255,.15) 50%,rgba(255,255,2" +
            "55,.15) 75%,transparent 75%,transparent);background-image:-moz-linear-gradient(4" +
            "5deg,rgba(255,255,255,.15) 25%,transparent 25%,transparent 50%,rgba(255,255,255," +
            ".15) 50%,rgba(255,255,255,.15) 75%,transparent 75%,transparent);background-image" +
            ":-o-linear-gradient(45deg,rgba(255,255,255,.15) 25%,transparent 25%,transparent " +
            "50%,rgba(255,255,255,.15) 50%,rgba(255,255,255,.15) 75%,transparent 75%,transpar" +
            "ent);background-image:linear-gradient(45deg,rgba(255,255,255,.15) 25%,transparen" +
            "t 25%,transparent 50%,rgba(255,255,255,.15) 50%,rgba(255,255,255,.15) 75%,transp" +
            "arent 75%,transparent);-webkit-background-size:40px 40px;-moz-background-size:40" +
            "px 40px;-o-background-size:40px 40px;background-size:40px 40px}.progress.active " +
            ".bar{-webkit-animation:progress-bar-stripes 2s linear infinite;-moz-animation:pr" +
            "ogress-bar-stripes 2s linear infinite;-ms-animation:progress-bar-stripes 2s line" +
            "ar infinite;-o-animation:progress-bar-stripes 2s linear infinite;animation:progr" +
            "ess-bar-stripes 2s linear infinite}body{font-weight:300}h3{font-size:26px}h4{fon" +
            "t-size:14px}.navbar .navbar-inner{background-image:none;-webkit-border-radius:0;" +
            "-moz-border-radius:0;border-radius:0;-webkit-box-shadow:none;-moz-box-shadow:non" +
            "e;box-shadow:none}.navbar-inverse .nav>li>a{text-shadow:none}.btn{padding:5px 12" +
            "px;text-shadow:none;background-image:none;border:none;-webkit-border-radius:0;-m" +
            "oz-border-radius:0;border-radius:0;-webkit-box-shadow:none;-moz-box-shadow:none;" +
            "box-shadow:none}select{color:#080808}.alert{text-shadow:none;-webkit-border-radi" +
            "us:0;-moz-border-radius:0;border-radius:0}.alert h1,.alert h2,.alert h3,.alert h" +
            "4,.alert h5,.alert h6,.alert-heading{color:#fff}[class^=icon-]{margin:0 2px;vert" +
            "ical-align:-2px}.progress{height:6px;background-color:#eee;background-image:none" +
            ";-webkit-border-radius:0;-moz-border-radius:0;border-radius:0;-webkit-box-shadow" +
            ":none;-moz-box-shadow:none;box-shadow:none}.progress .bar{background-color:#007f" +
            "ff}/*!\r\n  * Bootstrap Responsive v2.3.0\r\n  *\r\n  * Copyright 2012 Twitter, Inc\r\n " +
            " * Licensed under the Apache License v2.0\r\n  * http://www.apache.org/licenses/LI" +
            "CENSE-2.0\r\n  *\r\n  * Designed and built with all the love in the world @twitter b" +
            "y @mdo and @fat.\r\n  */@-ms-viewport{width:device-width}@media(min-width:1200px){" +
            ".row{margin-left:-30px}.row:after,.row:before{display:table;line-height:0;conten" +
            "t:\"\"}.row:after{clear:both}[class*=span]{float:left;min-height:1px;margin-left:3" +
            "0px}.container,.navbar-fixed-top .container{width:1170px}.span12{width:1170px}.s" +
            "pan9{width:870px}.span8{width:770px}.span4{width:370px}.span3{width:270px}input{" +
            "margin-left:0}}@media(min-width:768px) and (max-width:979px){.row{margin-left:-2" +
            "0px}.row:after,.row:before{display:table;line-height:0;content:\"\"}.row:after{cle" +
            "ar:both}[class*=span]{float:left;min-height:1px;margin-left:20px}.container,.nav" +
            "bar-fixed-top .container{width:724px}.span12{width:724px}.span9{width:538px}.spa" +
            "n8{width:476px}.span4{width:228px}.span3{width:166px}input{margin-left:0}}@media" +
            "(max-width:767px){body{padding-right:20px;padding-left:20px}.navbar-fixed-top{ma" +
            "rgin-right:-20px;margin-left:-20px}.container{width:auto}.row{margin-left:0}[cla" +
            "ss*=span]{display:block;float:none;width:100%;margin-left:0;-webkit-box-sizing:b" +
            "order-box;-moz-box-sizing:border-box;box-sizing:border-box}.span12{width:100%;-w" +
            "ebkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box}}@m" +
            "edia(max-width:480px){.nav-collapse{-webkit-transform:translate3d(0,0,0)}input[t" +
            "ype=checkbox]{border:1px solid #ccc}}@media(max-width:979px){body{padding-top:0}" +
            ".navbar-fixed-top{position:static}.navbar-fixed-top{margin-bottom:20px}.navbar-f" +
            "ixed-top .navbar-inner{padding:5px}.navbar .container{width:auto;padding:0}.nav-" +
            "collapse{clear:both}.nav-collapse .nav{float:none;margin:0 0 10px}.nav-collapse " +
            ".nav>li{float:none}.nav-collapse .nav>li>a{margin-bottom:2px}.nav-collapse .nav>" +
            "li>a{padding:9px 15px;font-weight:700;color:#777;-webkit-border-radius:3px;-moz-" +
            "border-radius:3px;border-radius:3px}.nav-collapse .nav>li>a:focus,.nav-collapse " +
            ".nav>li>a:hover{background-color:#f2f2f2}.navbar-inverse .nav-collapse .nav>li>a" +
            "{color:#999}.navbar-inverse .nav-collapse .nav>li>a:focus,.navbar-inverse .nav-c" +
            "ollapse .nav>li>a:hover{background-color:#111}.nav-collapse,.nav-collapse.collap" +
            "se{height:0;overflow:hidden}.navbar .btn-navbar{display:block}}@media(min-width:" +
            "980px){.nav-collapse.collapse{height:auto!important;overflow:visible!important}}" +
            "body{padding:54px 0 40px 0;overflow-y:scroll}body,button,input,select{font:400 1" +
            "4px/1.4em \"Segoe UI\",\"Open Sans\",Calibri,Candara,Arial,sans-serif}.navbar .nav{f" +
            "loat:left;margin-right:0}a{color:#06c;cursor:pointer}h3,h4{letter-spacing:-.01em" +
            ";margin:0;line-height:normal}h3{font-size:26px}h4{font-size:16px}.alert h1,.aler" +
            "t h2,.alert h3,.alert h4,.alert h5,.alert h6,.alert-heading{color:inherit}.alert" +
            "-info{color:#3a87ad;background-color:#d9edf7}.navbar-inverse .navbar-inner{backg" +
            "round-color:#68217a;-webkit-filter:none;filter:none}.navbar-inverse .btn-navbar{" +
            "background:0 0;margin-top:14px}.navbar-inverse .btn-navbar:active,.navbar-invers" +
            "e .btn-navbar:focus,.navbar-inverse .btn-navbar:hover{background:#442359}body>se" +
            "ction>.container{padding-top:12px}.navbar .nav>li>a{text-shadow:none;padding-top" +
            ":18px;font-size:14px;text-transform:uppercase}.navbar-inverse .nav-collapse .nav" +
            ">li>a{color:#fff;padding-left:0}.navbar-inverse .nav>li>a.nav-item:focus,.navbar" +
            "-inverse .nav>li>a.nav-item:hover{background-color:rgba(0,0,0,.12)}.navbar .logo" +
            "{padding:16px 12px 0 0;height:35px;display:block;float:left}.navbar .logo a{colo" +
            "r:#fff;font-size:24px;letter-spacing:-1px}.navbar-fixed-top{z-index:500}#gh-link" +
            "{display:none;position:fixed;top:0;right:0;border:0;margin:0;z-index:1000}@media" +
            " (min-width:980px){#gh-link{display:block}}@media (min-width:980px){.navbar .nav" +
            "{float:right}.navbar-inverse .nav-collapse .nav>li>a{padding-left:15px}}@media (" +
            "max-width:979px){body{padding:inherit}.navbar-fixed-top{margin-right:inherit;mar" +
            "gin-left:inherit;margin-bottom:0}.navbar-fixed-top .navbar-inner{padding:0 20px}" +
            ".navbar .container{width:724px}}@media (max-width:767px){.navbar .container{widt" +
            "h:100%}}@media (max-width:480px){.navbar .logo a{display:none}}.try .editor.row{" +
            "padding:18px 0}.try .row h4{padding-bottom:6px}.try .editor.row .control-label{d" +
            "isplay:inline-block;position:relative;top:-4px;margin-right:4px}.try .editor .ed" +
            "itor-frame{position:relative}.try .editor .editor-frame #diff-editor,.try .edito" +
            "r .editor-frame #editor{height:400px;margin-bottom:10px;border:1px solid #eee}.t" +
            "ry .editor .editor-frame .loading{position:absolute;height:100%;width:100%;backg" +
            "round-color:rgba(255,255,255,.5);margin:0 auto;display:none;z-index:100}.try .ed" +
            "itor .editor-frame .progress{width:50%;margin:15% auto 0}.try .editor .editor-fr" +
            "ame .progress .bar{width:100%;background-color:#4bb1cf}.try .editor .editor-fram" +
            "e #diff-editor .alert,.try .editor .editor-frame #editor .alert{margin:18% auto " +
            "0;width:30%;text-align:center;color:#b94a48;background-color:#f2dede;border-colo" +
            "r:#eed3d7}@media (min-width:1200px){.try .editor .row{margin-left:0}}@media (max" +
            "-width:767px){.try .container{margin:0 24px}.try .editor>.span9 .row .span4{floa" +
            "t:left;width:50%}.try .editor h4{margin-top:0}}@media (max-width:520px){.try .ed" +
            "itor>.span3 h4,.try .editor>.span3 p{display:none}}@media (max-width:320px){.try" +
            " .editor>.span9{display:none}}</style>\r\n   \r\n<body style=\"height: 500px;width: 1" +
            "00%;margin: 0;\">\r\n     <pre data-preload=\"index/samples/diff.lhs.txt\" style=\"dis" +
            "play:none\">\r\nDATAS SEGMENT\r\n;此处输入数据段代码  \r\nDATAS ENDS\r\n\r\nSTACKS SEGMENT\r\n;此处输入堆栈段" +
            "代码\r\nSTACKS ENDS\r\n\r\nCODES SEGMENT\r\nASSUME CS:CODES,DS:DATAS,SS:STACKS\r\nSTART:\r\nMO" +
            "V AX,DATAS\r\nMOV DS,AX\r\n;此处输入代码段代码\r\nMOV AH,4CH\r\nINT 21H\r\nCODES ENDS\r\nEND START\r\n " +
            "</pre>\r\n      <pre data-preload=\"index/samples/diff.rhs.txt\" style=\"display:none" +
            "\">\r\nDATAS SEGMENT\r\n    DB \'Hello world$\'\r\nDATAS ENDS\r\n\r\nSTACKS SEGMENT\r\n;此处输入堆栈段" +
            "代码\r\nSTACKS ENDS\r\n\r\nCODES SEGMENT\r\nASSUME CS:CODES,DS:DATAS,SS:STACKS\r\nSTART:\r\nMO" +
            "V AX,DATAS\r\nMOV DS,AX\r\n;此处输入代码段代码\r\nMOV AH,4CH\r\nINT 21H\r\nCODES ENDS\r\nEND START\r\n<" +
            "/pre>\r\n\r\n<section class=\"try\" style=\"height: 500px;width: 100%;margin: 0;\">\r\n\t\t\t" +
            "\t<div class=\"span9\">\r\n\t\t\t\t\t<div class=\"row\">\r\n\t\t\t\t\t\t<div class=\"span4\" style=\"di" +
            "splay: none;\">\r\n\t\t\t\t\t\t\t<label class=\"control-label\">Language</label>\r\n\t\t\t\t\t\t\t<se" +
            "lect class=\"language-picker\"></select>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div cla" +
            "ss=\"editor-frame\">\r\n\t\t\t\t\t\t<div class=\"loading editor\" style=\"display: none;\">\r\n\t" +
            "\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div id=\"editor\"></div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n" +
            "\t\t\t<hr>\r\n\t\t\t<div class=\"editor row\" >\r\n\t\t\t\t<div class=\"span9\">\r\n\t\t\t\t\t<div class=" +
            "\"row\">\r\n\t\t\t\t\t\t<div class=\"span8\">\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div class=\"e" +
            "ditor-frame\">\r\n\t\t\t\t\t\t<div class=\"loading diff-editor\" style=\"display: none;\">\r\n\t" +
            "\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div id=\"diff-editor\"></div>\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t</d" +
            "iv>\r\n\t\t</div>\r\n\t</section>\r\n\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs" +
            "/jquery/1.9.1/jquery.min.js\" integrity=\"sha256-wS9gmOZBqsqWxgIVgA8Y9WcQOa7PgSIX+" +
            "rPA0VL2rbQ=\" crossorigin=\"anonymous\"></script>\r\n\t<script src=\"https://cdnjs.clou" +
            "dflare.com/ajax/libs/twitter-bootstrap/2.3.0/bootstrap.min.js\" integrity=\"sha256" +
            "-u+l2mGjpmGK/mFgUncmMcFKdMijvV+J3odlDJZSNUu8=\" crossorigin=\"anonymous\"></script>" +
            "\r\n\t<script>var require = { paths: { \'vs\': \'node_modules/monaco-editor/min/vs\' } " +
            "};</script>\r\n\t<script src=\"../node_modules/monaco-editor/min/vs/loader.js\"></scr" +
            "ipt>\r\n\t<script src=\"../node_modules/monaco-editor/min/vs/editor/editor.main.nls." +
            "js\"></script>\r\n\t<script src=\"../node_modules/monaco-editor/min/vs/editor/editor." +
            "main.js\"></script>\r\n\t<script>/// <reference path=\"../../release/monaco.d.ts\" />\r" +
            "\n\r\n\r\n\r\nvar editor = null, diffEditor = null;\r\n\r\n$(document).ready(function() {\r\n" +
            "\trequire([\'vs/editor/editor.main\'], function () {\r\n\t\tvar MODES = (function() {\r\n" +
            "\t\t\tvar modesIds = monaco.languages.getLanguages().map(function(lang) { return la" +
            "ng.id; });\r\n\t\t\tmodesIds.sort();\r\n\r\n\t\t\treturn modesIds.map(function(modeId) {\r\n\t\t" +
            "\t\treturn {\r\n\t\t\t\t\tmodeId: modeId,\r\n\t\t\t\t\tsampleURL: \'index/samples/sample.\' + mode" +
            "Id + \'.txt\'\r\n\t\t\t\t};\r\n\t\t\t});\r\n\t\t})();\r\n\r\n\t\tvar startModeIndex = 0;\r\n\t\tfor (var i " +
            "= 0; i < MODES.length; i++) {\r\n\t\t\tvar o = document.createElement(\'option\');\r\n\t\t\t" +
            "o.textContent = MODES[i].modeId;\r\n\t\t\tif (MODES[i].modeId === \'typescript\') {\r\n\t\t" +
            "\t\tstartModeIndex = i;\r\n\t\t\t}\r\n\t\t\t\r\n\t\t}\r\n\t\t$(\".language-picker\")[0].selectedIndex " +
            "= 0;\r\n\t\tloadSample(MODES[startModeIndex]);\r\n\t\t$(\".language-picker\").change(funct" +
            "ion() {\r\n\t\t\tloadSample(MODES[this.selectedIndex]);\r\n\t\t});\r\n\r\n\t\t$(\".theme-picker\"" +
            ").change(function() {\r\n\t\t\tchangeTheme(this.selectedIndex);\r\n\t\t});\r\n\r\n\t\tloadDiffS" +
            "ample();\r\n\r\n\t\t$(\'#inline-diff-checkbox\').change(function () {\r\n\t\t\tdiffEditor.upd" +
            "ateOptions({\r\n\t\t\t\trenderSideBySide: !$(this).is(\':checked\')\r\n\t\t\t});\r\n\t\t});\r\n\t});" +
            "\r\n\r\n\twindow.onresize = function () {\r\n\t\tif (editor) {\r\n\t\t\teditor.layout();\r\n\t\t}\r" +
            "\n\t\tif (diffEditor) {\r\n\t\t\tdiffEditor.layout();\r\n\t\t}\r\n\t};\r\n});\r\n\r\nvar preloaded = " +
            "{};\r\n(function() {\r\n\tvar elements = Array.prototype.slice.call(document.querySel" +
            "ectorAll(\'pre[data-preload]\'), 0);\r\n\r\n\telements.forEach(function(el) {\r\n\t\tvar pa" +
            "th = el.getAttribute(\'data-preload\');\r\n\t\tpreloaded[path] = el.innerText || el.te" +
            "xtContent;\r\n\t\tel.parentNode.removeChild(el);\r\n\t});\r\n})();\r\n\r\nfunction xhr(url, c" +
            "b) {\r\n\tif (preloaded[url]) {\r\n\t\treturn cb(null, preloaded[url]);\r\n\t}\r\n\t$.ajax({\r" +
            "\n\t\ttype: \'GET\',\r\n\t\turl: url,\r\n\t\tdataType: \'text\',\r\n\t\terror: function () {\r\n\t\t\tcb" +
            "(this, null);\r\n\t\t}\r\n\t}).done(function(data) {\r\n\t\tcb(null, data);\r\n\t});\r\n}\r\n\r\nfun" +
            "ction loadSample(mode) {\r\n\t$(\'.loading.editor\').show();\r\n\txhr(mode.sampleURL, fu" +
            "nction(err, data) {\r\n\t\tif (err) {\r\n\t\t\tif (editor) {\r\n\t\t\t\tif (editor.getModel()) " +
            "{\r\n\t\t\t\t\teditor.getModel().dispose();\r\n\t\t\t\t}\r\n\t\t\t\teditor.dispose();\r\n\t\t\t\teditor =" +
            " null;\r\n\t\t\t}\r\n\t\t\treturn;\r\n\t\t}\r\n\r\n\t\tif (!editor) {\r\n\t\t\t$(\'#editor\').empty();\r\n\t\t\t" +
            "editor = monaco.editor.create(document.getElementById(\'editor\'), {\r\n\t\t\t\tmodel: n" +
            "ull,\r\n\t\t\t});\r\n\t\t}\r\n\r\n\t\tvar oldModel = editor.getModel();\r\n\t\tvar newModel = monac" +
            "o.editor.createModel(data, mode.modeId);\r\n\t\teditor.setModel(newModel);\r\n\t\tif (ol" +
            "dModel) {\r\n\t\t\toldModel.dispose();\r\n\t\t}\r\n\t\t$(\'.loading.editor\').fadeOut({ duratio" +
            "n: 300 });\r\n\t})\r\n}\r\n\r\nfunction loadDiffSample() {\r\n\r\n\t$(\'.loading.diff-editor\')." +
            "show();\r\n\r\n\tvar lhsData = null, rhsData = null, jsMode = null;\r\n\r\n\txhr(\'index/sa" +
            "mples/diff.lhs.txt\', function(err, data) {\r\n\t\tif (err) {\r\n\t\t\treturn onError();\r\n" +
            "\t\t}\r\n\t\tlhsData = data;\r\n\t\tonProgress();\r\n\t})\r\n\txhr(\'index/samples/diff.rhs.txt\'," +
            " function(err, data) {\r\n\t\tif (err) {\r\n\t\t\treturn onError();\r\n\t\t}\r\n\t\trhsData = dat" +
            "a;\r\n\t\tonProgress();\r\n\t})\r\n\r\n\tfunction onProgress() {\r\n\t\tif (lhsData && rhsData) " +
            "{\r\n\t\t\tdiffEditor = monaco.editor.createDiffEditor(document.getElementById(\'diff-" +
            "editor\'), {\r\n\t\t\t\tenableSplitViewResizing: false\r\n\t\t\t});\r\n\r\n\t\t\tvar lhsModel = mon" +
            "aco.editor.createModel(lhsData, \'abap\');\r\n\t\t\tvar rhsModel = monaco.editor.create" +
            "Model(rhsData, \'abap\');\r\n\r\n\t\t\tdiffEditor.setModel({\r\n\t\t\t\toriginal: lhsModel,\r\n\t\t" +
            "\t\tmodified: rhsModel\r\n\t\t\t});\r\n\r\n\t\t\t$(\'.loading.diff-editor\').fadeOut({ duration:" +
            " 300 });\r\n\t\t}\r\n\t}\r\n}\r\n\r\n</script>\r\n\r\n</body>\r\n</html>")]
        public string diffScript {
            get {
                return ((string)(this["diffScript"]));
            }
        }
    }
}
